# Generated by Django 3.2 on 2021-04-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210419_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Пользователь'),
        ),
    ]
