# Generated by Django 3.2 on 2021-04-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Номер обращения'),
        ),
    ]
