# Generated by Django 3.2 on 2021-04-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_application_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='id_name',
        ),
    ]
