# Generated by Django 3.2 on 2021-04-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_rename_name_application_id_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='id_name',
        ),
    ]
