# Generated by Django 3.2 on 2021-04-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_application_id_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='date_of_closed',
        ),
    ]
