# Generated by Django 3.2 on 2021-04-21 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_detail', to='portal.service', verbose_name='Услуга'),
        ),
    ]
